apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: sftp-gcloud-key
  namespace: {{ .Values.coords.namespace }}
data:
  gcloud-key.json: {{ .Files.Get (print "keys/storage/" .Values.coords.projectId ".json") | b64enc }}
